title: PenTest Notes
description: Very much a work in progress...
theme: just-the-docs
color_scheme: dark

url: https://tranquil-rage.github.io/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
